### ISSUE TITLE
Not working with Drupal

### ISSUE THREAD

**Issue by khuongtp** [eriksoderblom/alpine-apache-php#9]
It might be a little bit off topic but I couldn't find any solution to this when I try installing a Drupal site, I think we're missing some extensions here. Any help would appreciated
![image](https://user-images.githubusercontent.com/62872729/195785293-494e334d-8d52-4885-8380-3881bfbf80eb.png)

**Comment by eriksoderblom** [comment]
I'm pretty sure this is not a missing extension, since all extensions mentioned on Drupals [php requirements page](https://www.drupal.org/docs/system-requirements/php-requirements) are installed.
The error logs doesn't really point to any missing extension either, as far as I can tell.
I think you'll be better of asking for help in their community.
